### ISSUE TITLE
en/api/components-nuxt-child.md の翻訳

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.docs.nuxtjs#10]
https://github.com/nuxt/docs/commit/b000302 の差分を翻訳します。

翻訳の流れは [Nuxt 2.0 ドキュメント翻訳 · Issue #9 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/9) を参照してください。

**Comment by shika358** [comment]
これ、やりますね

**Comment by shika358** [comment]
https://github.com/nuxt/docs/pull/828

このコミットにて翻訳済でした。
対応遅くて申し訳ないです〜

**Comment by aytdm** [comment]
@shika358
作業しちゃってくれたらとっても嬉しかです！😊

**Comment by shika358** [comment]
遅くなってます、今日か明日作業します 🙏

**Comment by inouetakuya** [comment]
[ja: Update components-nuxt-child.md by shika358 · Pull Request #1020 · nuxt/docs](https://github.com/nuxt/docs/pull/1020)
