### ISSUE TITLE
en/api/configuration-router.md の翻訳

### ISSUE THREAD

**Issue by aytdm** [vuejs-jp/ja.docs.nuxtjs#103]
### 翻訳対象

/api/configuration-router.md
b000302..e53272a 間の差分の翻訳をお願いします。
詳細な差分は `git diff` コマンドで見るか、いのうえさんが用意してくださった[こちらの gist](https://gist.github.com/inouetakuya/4b231c5e634e5e7d0f80856d3eb3691d) を参照してください。

### 翻訳の流れ

まずはこの issue にコメントで翻訳する意思表示をお願いします🙋
それ以降の流れは [#37ドキュメント翻訳 2019 春の陣](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/37#issue-415991098) を参照してください。

### 翻訳スタイル

Vue.js に合わせています。
スタイルについては[こちら](https://github.com/vuejs-jp/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md#%E7%BF%BB%E8%A8%B3%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB)を参照してください。

**Comment by doutori** [comment]
こちら対応いたします！

**Comment by doutori** [comment]
と思ったのですが、すでに修正済み + 改行が足されているのみのようでした〜

**Comment by aytdm** [comment]
遅くなりました:bow: ご確認ありがとうございます！
おそらく以下の箇所が未翻訳なので翻訳をお願いします:pray:

```md
# https://github.com/nuxt/docs/blob/5cd0c2d5fd96adcf5fe3516505cb46a367b4db5c/en/api/configuration-router.md#L17-19

This can be useful if you need to serve Nuxt as a different context root, from within a bigger Web site. Notice that you may, or may not set up a Front Proxy Web Server.

If you want to have a redirect to router.base, you can do so using a Hook, see Redirect to router.base when not on root.
```

**Comment by doutori** [comment]
申し訳ありません、完全に見間違えておりました 💦💦💦
翻訳を行い、PRを投げさせていただきましたので、お手数ですがご確認お願いいたします。
