### ISSUE TITLE
en/api/configuration-env.md の翻訳

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.docs.nuxtjs#12]
https://github.com/nuxt/docs/commit/b000302 の差分を翻訳します。

翻訳の流れは [Nuxt 2.0 ドキュメント翻訳 · Issue #9 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/9) を参照してください。

**Comment by rascate** [comment]
翻訳担当します！

**Comment by inouetakuya** [comment]
@rascate 

申し出ありがとうございます！ただ、[ドキュメント翻訳 2018 秋の陣 · Issue #5 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/5) の流れで、他の方が下記プルリクで対応中ですので、こちらの Issue はクローズさせてください。すみません〜 🙏 

* [ja: Update ja/api/configuration-env.md by 53able · Pull Request #933 · nuxt/docs](https://github.com/nuxt/docs/pull/933#pullrequestreview-169601514)
