### ISSUE TITLE
型の表記を en/ に合わせて Boolean / Object など英語表記で統一する

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.docs.nuxtjs#126]
型の表記が現状 `ブーリアン` や `オブジェクト` などのカタカナ表記になっていますが、これらを en/ に合わせて Boolean / Object など英語表記で統一します。

### なぜ？

- Boolean / Object などの表記のほうが分かりやすいと考えるため
- Vue.js / Vuex / Vue Router などの他の公式ドキュメントでも、カタカナ表記ではなく英語表記になっていることも参考にした

### その他詳細

経緯及び詳細は下記 Slack のやり取りを参照してください。

- https://vuejs-jp.slack.com/archives/C1P227P7V/p1552137243007300

**Comment by resessh** [comment]
`ja/*` に雑に正規表現で引っ掛けた結果、変更の必要がありそうなの以下でした

```
   1 - **型:** `関数` または `非同期関数`
   1 - **型:** `文字列` または `関数`（デフォルト: `'default'`）
   1 - **型:** `文字列` または `オブジェクト` または `関数`
   1 - **型:** `ブーリアン` or `配列` (デフォルト: `[]`)
   1 - **型:** `ブーリアン`（デフォルト: `false`）
   1 - **型:** `オブジェクト` または `関数`
   1 - 型 `文字列`
   1 - 型: `配列<String>`
   1 - 型: `配列<string | RegExp>`
   1 - 型: `配列`、`オブジェクト`（推奨）、`関数` または `ブーリアン`
   1 - 型: `文字列` or `ブーリアン`
   1 - 型: `ブーリアン` または `オブジェクト`
   1 - 型: `ブーリアン` または `オブジェクト` または `文字列`
   2 - **型:** `関数`
   2 - 型: `数値`
   2 - 型: `文字列` または `配列`
   2 - 型: `文字列` または `オブジェクト`
   2 - 型: `オブジェクト` または `ブーリアン`
   7 - 型: `配列`
   7 - 型: `関数`
  10 - 型: `文字列`
  11 - 型: `ブーリアン`
  19 - 型: `オブジェクト`
```

言い出しっぺなのでこちらのPR作ってみますね

**Comment by aytdm** [comment]
resessh さんありがとうございます！
遅くなりましたが修正対象のファイルを列挙しました（typo や漏れがあったらごめんなさい:pray:）
思ったより量が多いので分担しましょう:muscle:

api/configuration-* とそれ以外という分け方はいかがでしょうか？
もしすでに対応中のものがあれば教えていただけると助かります

+ [ ] api/components-no-ssr.md
+ [ ] api/components-nuxt.md
+ [ ] api/configuration-build.md
+ [ ] api/configuration-builddir.md
+ [ ] api/configuration-css.md
+ [ ] api/configuration-dev.md
+ [ ] api/configuration-dir.md
+ [ ] api/configuration-env.md
+ [ ] api/configuration-generate.md
+ [ ] api/configuration-head.md
+ [ ] api/configuration-hooks.md
+ [ ] api/configuration-ignore.md
+ [ ] api/configuration-loading.md
+ [ ] api/configuration-plugins.md
+ [ ] api/configuration-rootdir.md
+ [ ] api/configuration-router.md
+ [ ] api/configuration-server.md
+ [ ] api/configuration-servermiddlewre.md
+ [ ] api/configuration-srcdir.md
+ [ ] api/configuration-transition.md
+ [ ] api/configuration-watchers.md
+ [x] api/context.md
  + #1218 で 53 さんが対応してくださっています
+ [ ] api/index.md
+ [ ] api/internals-module-container.md
+ [ ] api/nuxt-render-and-get-window.md
+ [ ] api/nuxt-render-route.md
+ [ ] api/nuxt-render.md
+ [ ] api/pages-fetch.md
+ [ ] api/pages-head.md
+ [ ] api/pages-layout.md
+ [ ] api/pages-middleware.md
+ [ ] api/pages-scrolltotop.md
+ [ ] api/pages-transition.md
+ [ ] api/pages-validate.md
+ [ ] api/pages-watchquery.md

**Comment by resessh** [comment]
@aytdm 気づくのが遅れてしまいました…
ありがとうございます…！！！

今configuration周りから着手していたので、もしよければそこを境に分担していただけるとありがたいです！

**Comment by resessh** [comment]
@aytdm ついでなのでやってしまいました… 🙇 
レビューをいただけるとありがたいです 🙏

**Comment by aytdm** [comment]
@resessh ありがとうございます！承知しました
