### ISSUE TITLE
コミット前に自動で textlint:ja:fix をかけるようにする

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.docs.nuxtjs#127]
@potato4d @aytdm 

どうでしょう？特に要件について、この点にも注意したほうが良さそうとかあればコメントいただきたいです :pray:

## 解決したい課題

レビューをしながら、文書のフォーマットについて（例えば半角スペースを入れてくださいとか）コメントするの生産的じゃないなーと思った。

## 自動で textlint かけるようにしたい

```shell
yarn textlint:ja
yarn textlint:ja:fix --dry-run
yarn textlint:ja:fix
```

というコマンドは用意しているんだけど、これを日本語の翻訳に関わる人たち全員にしてもらうのもちょっとなーと思った（周知とか徹底とか）ので、コミット前に自動でしたい。

## 要件

- git commit 前に自動で `yarn textlint:ja:fix` が実行されること
- ja/ 以外に影響がないこと
- 変更を加えたファイル以外に影響がないこと（git のステージング状態のファイルのみ処理対象にする）

## 参考

下記あたりを利用するイメージでいます。

- [okonet/lint-staged: 🚫💩 — Run linters on git staged files](https://github.com/okonet/lint-staged)
- [typicode/husky: 🐶 Git hooks made easy](https://github.com/typicode/husky)

**Comment by aytdm** [comment]
@inouetakuya ありがとうございます。仰る通りここは楽したいですね...！ツールの選定もいいと思います:+1: ただこの運用方法だと、lint がかからないケースが起き得るのと、ja ディレクトリ以外のコミットの際もチェックが走ることの2点が気になりました。

1. lint がかからないケースが起き得る
例えば、依存関係をインストールしていない人や、依存関係をインストールしているが、yarn がない人（WindowsOSのみ。MacOS だと yarn のインストールを促される）
対策：<br>・翻訳の都度周知してインストール＆チェックをお願いする<br>・`ja.docs.nuxtjs` 内に Wiki を作成<br>＃ 都度周知は今回の目的（`周知とか徹底とか`）からすると微妙でしょうか...
2. ja ディレクトリ以外のコミットでもチェックが走る
ja/ 以外に影響がなくとも、チェックが走るのは気になりますし確認が必要と思います:thinking: ※軽く試しただけなので回避方法があるなら勘違いです:bow:

Wiki は一度作ってしまえばメンテナンスするコストは高くないのでありだと思っています

**Comment by inouetakuya** [comment]
@aytdm 

コメントありがとうございます！考慮していない箇所があったので大変助かりました！:satisfied:

> 1. lint がかからないケースが起き得る

なるほどなるほど（そこまで考えていませんでした :sweat_smile:

リポジトリをよくみたら、nuxt/docs リポジトリは npm を使う想定のようなので（yarn.lock もありますが...）、一旦 npm textlint:ja:fix が走るかたちで進めようと思うので、Yarn がない人については一旦置いておきます。

依存関係をインストールしていない人は、たしかに lint がかからないですねぇ...

なので、今回の「春の陣」のように Issue 立てて募るときにはそこに書くようにしますね。

> 2. ja ディレクトリ以外のコミットでもチェックが走る

これは仕組み上、防ぐ方法を思いつかないです。ただ、私見では、チェックが走っても、それが気にならない程度の時間であれが許容範囲かなと考えていて、

- ja ディレクトリ以外のコミットのときにどのくらいチェックに時間がかかるか計測する
- nuxt/docs へのプルリクで、本件について触れる

という方向で進めたいと思います。

**Comment by inouetakuya** [comment]
> ja ディレクトリ以外のコミットのときにどのくらいチェックに時間がかかるか計測する

数回試しましたが `ja/**/*.md` が編集されていないときは textlint のチェックに 0.5秒くらいしかかからなかったので、許容範囲かと思いました。

```
[@GISELE.local ja.docs.nuxtjs]$ yarn lint-staged
yarn run v1.15.2
$ /Users/inouetakuya/src/github.com/inouetakuya/ja.docs.nuxtjs/node_modules/.bin/lint-staged
No staged files match any of provided globs.
✨  Done in 0.58s.
```

**Comment by inouetakuya** [comment]
プルリクエストを作りましたー :octocat:

- [textlint:ja:fix on pre-commit with lint-staged and husky by inouetakuya · Pull Request #1301 · nuxt/docs](https://github.com/nuxt/docs/pull/1301)
