### ISSUE TITLE
[doc] fix(typo): Fix menu link

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.docs.nuxtjs#129]
本家のドキュメントに更新がありました :page_facing_up:
Original:https://github.com/nuxt/docs/commit/8dc6d11b12d7709a06d5dadb5e36fa856de22359

**Comment by hidetzu** [comment]
日本語翻訳版の該当箇所を確認しましたが、変更の必要はないと思います。
問題無いようでしたらクローズをお願いします。

**Comment by aytdm** [comment]
@hidetzu おっしゃる通り、変更不要のためクローズします。確認してくださってありがとうございます:+1:
