### ISSUE TITLE
[doc] ja: Add guide/typescript.md to ja/

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.docs.nuxtjs#141]
本家のドキュメントに更新がありました :page_facing_up:
Original:https://github.com/nuxt/docs/commit/c3baf64f7a438524628bcffda43111b6e35114ed

**Comment by aytdm** [comment]
https://github.com/nuxt/docs/commit/3056b1a51a47f2676da157fa3ddc3745ae1f0e52 で対応済みのためクローズ
