### ISSUE TITLE
[doc] en: add azure portal deployment guide

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.docs.nuxtjs#144]
本家のドキュメントに更新がありました :page_facing_up:
Original:https://github.com/nuxt/docs/commit/a8ec0f42eddb14098192dc70cc8ed6e6621913eb

**Comment by tell-k** [comment]
@aytdm もしまだ未着手のようだったら、これやろうかと思いますがいかがでしょうかー？ 先に他のをやって欲しいとかあれば、そっちをやるので教えてくださいー！

**Comment by aytdm** [comment]
@tell-k ありがとうございます。とても助かります…！お言葉に甘えてよろしくお願いします🙏

**Comment by tell-k** [comment]
@aytdm 了解です！確認ありがとうございますー

**Comment by aytdm** [comment]
@tell-k 今このファイルに対してPR（[#1441](https://github.com/nuxt/docs/pull/1441)）を出しており、もし翻訳に取りかかっていたらマージ後 取り込んで頂けると助かります。（コードブロック内が真っ白だったので、言語識別子を追加しました）
また、丸投げしてすみません:bow: もしお忙しいようでしたら遠慮なく仰ってください

**Comment by tell-k** [comment]
@aytdm 了解です。取り込んでおきます！ 

そして遅れてすいません。今週のどこかでは一回PRだすようにしますー。

**Comment by aytdm** [comment]
@tell-k ありがとうございます！
あ、急かすつもりは全くなく、tell-k さんのペースで問題ありません
元々私がすると言っていたものを引き受けてくださっているので申し訳なく…分担でも巻取りでも、何かあればいつでも言ってください👍

**Comment by aytdm** [comment]
@tell-k こちら巻き取ります:raised_hands:

**Comment by tell-k** [comment]
@aytdm 

すいません。自分でやるといいながら完全に忘れてました...
巻き取りありがとうございます 🙏
