### ISSUE TITLE
Nuxt.js 公式ドキュメント日本語翻訳ガイドを作成する

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.docs.nuxtjs#146]
### この Issue の完了条件

- [x] [jp.vuejs.org/CONTRIBUTING.md at lang-ja · vuejs/jp.vuejs.org](https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md) を参考にして翻訳ガイドを作成する
- [x] 翻訳ガイドの内容についてレビューしてもらう
- [x] 翻訳ガイドへのリンクを https://github.com/nuxt/docs/blob/master/README.md に作成する
- [x] vuejs-jp の Slack `#translation` チャンネルで、翻訳ガイドについて周知する

**Comment by inouetakuya** [comment]
@potato4d @aytdm

[Nuxt.js 公式ドキュメント日本語翻訳ガイド](https://github.com/vuejs-jp/ja.docs.nuxtjs/wiki) を作成したので、

- 分かりにくい箇所がないか？

という観点からレビューをお願いします :pray:

**Comment by inouetakuya** [comment]
GitHub のプルリクと Issue とを連携させる `resolve` キーワードって、リポジトリを跨いでも効果があるか不明だったのですが、下記で実験してみたら効果があった（= プルリクをマージすると Issue がクローズされた）ので、日本語翻訳ガイドに追記します。

- [ja: add modules links by inouetakuya · Pull Request #1342 · nuxt/docs](https://github.com/nuxt/docs/pull/1342)
- [[doc] docs(guide): Add modules links · Issue #133 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/133)

**Comment by aytdm** [comment]
@inouetakuya ありがとうございます！Looks Great To Me です:+1: もろもろタスクがある中、ありがとうございます

**Comment by inouetakuya** [comment]
こちらこそ！レビューありがとうございました！:laughing:
