### ISSUE TITLE
en/api/configuration-modulesdir.md の翻訳

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.docs.nuxtjs#15]
https://github.com/nuxt/docs/commit/b000302 の差分を翻訳します。

翻訳の流れは [Nuxt 2.0 ドキュメント翻訳 · Issue #9 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/9) を参照してください。

**Comment by ry0-ta** [comment]
@inouetakuya 
こちら、担当させていただければと思います！

**Comment by ry0-ta** [comment]
@inouetakuya 
差分が無いようにに見えたのですが、もしかして以下で対応済みだったりしますか？？
https://github.com/nuxt/docs/pull/795

**Comment by aytdm** [comment]
@ry0-ta 遅くなりました、コメントありがとうございます。
ご指摘のとおり、ryota-yamamotoさんが翻訳されてますね・・・！
確認不足ですみません～！本件、翻訳済みでcloseとさせてください🙇

**Comment by ry0-ta** [comment]
@aytdm 
承知しました！他にもう一つ担当あるのでそちらやりますね。  
ありがとうございました。
