### ISSUE TITLE
[doc] fix(typescript): Add description

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.docs.nuxtjs#152]
本家のドキュメントに更新がありました :page_facing_up:
Original:https://github.com/nuxt/docs/commit/9e82bc94843f7b710aa02cf83d0659ee3a11236e

**Comment by inouetakuya** [comment]
[ja: update guide/typescript.md by aytdm · Pull Request #1375 · nuxt/docs](https://github.com/nuxt/docs/pull/1375) で対応していただいているのでクローズしますー
