### ISSUE TITLE
[doc] Add FAQ about loading audio files with Webpack

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.docs.nuxtjs#153]
本家のドキュメントに更新がありました :page_facing_up:
Original:https://github.com/nuxt/docs/commit/4013e39de42cb2bc25ff2b33ef96025a6ebbabf1

**Comment by noliaki** [comment]
やります🙋

**Comment by aytdm** [comment]
ありがとうございます！よろしくお願いします

**Comment by aytdm** [comment]
ありがとうございます！よろしくお願いします
