### ISSUE TITLE
[doc] docs(menu): Add audio files FAQ in menu

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.docs.nuxtjs#154]
本家のドキュメントに更新がありました :page_facing_up:
Original:https://github.com/nuxt/docs/commit/19945d8cb0d8d36cb8b1ee76b6a350054baffcff

**Comment by noliaki** [comment]
やります🙋

**Comment by aytdm** [comment]
ありがとうございます！よろしくお願いします
