### ISSUE TITLE
[doc] chore(docs): Update version, fix typo for audio files

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.docs.nuxtjs#155]
本家のドキュメントに更新がありました :page_facing_up:
Original:https://github.com/nuxt/docs/commit/239a49f8e489bf107240d9608217302ddba1b6b5

**Comment by aytdm** [comment]
lang.json は対応済み
Ref: https://github.com/nuxt/docs/pull/1356

**Comment by noliaki** [comment]
やります🙋
