### ISSUE TITLE
en/api/configuration-render.md の翻訳

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.docs.nuxtjs#16]
https://github.com/nuxt/docs/commit/b000302 の差分を翻訳します。

翻訳の流れは [Nuxt 2.0 ドキュメント翻訳 · Issue #9 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/9) を参照してください。

**Comment by resessh** [comment]
こちら翻訳完了しているのを確認しました

**Comment by aytdm** [comment]
@resessh 
コメントありがとうございます。
ご指摘のとおり、tell-kさんが翻訳されてますね。
確認不足ですみません～！本件、翻訳済みでcloseとさせてください:bow:
