### ISSUE TITLE
Slack との連携

### ISSUE THREAD

**Issue by aytdm** [vuejs-jp/ja.docs.nuxtjs#163]
@inouetakuya @potato4d 

Slack と連携したほうが気付きやすいかなと思います:+1: 
権限をもっていないので、問題がなければお二人のどちらかに対応をお願いしたいです:pray:

**Comment by inouetakuya** [comment]
@aytdm 

よさそうです！`jp.vuejs.org` リポジトリと合わせた設定にしてみました！

![image](https://user-images.githubusercontent.com/634357/57583844-b4376800-750f-11e9-8927-6d0a3303150e.png)

---

@kazupon 

上の設定をする際に、当初、設定を「追加」するつもりで操作を行っていたのですが、実際には元からあった設定を「編集」してしまったようです。

`jp.vuejs.org` リポジトリについても設定しているので大丈夫だとは思いますが、何か問題等ありましたら、教えてください 🙇

**Comment by inouetakuya** [comment]
### この Issue の完了条件

- [ ] ja.docs.nuxtjs リポジトリで Issue が作成されたタイミングなどで Slack へ通知が正常に送信されること
- [ ] jp.vuejs.org リポジトリで Issue が作成されたタイミングなどで Slack へ通知が正常に送信されること

**Comment by aytdm** [comment]
@inouetakuya 迅速なご対応ありがとうございました！
