### ISSUE TITLE
en/api/configuration-generate.md の翻訳

### ISSUE THREAD

**Issue by aytdm** [vuejs-jp/ja.docs.nuxtjs#166]
### 翻訳対象

ja/api/configuration-generate.md

最新（[38aaf2d](https://github.com/nuxt/docs/commits/master)）との差分の翻訳をお願いします。（bot 稼働前に未翻訳だったものの翻訳が目的です）

### 翻訳の流れ

[Wiki](https://github.com/vuejs-jp/ja.docs.nuxtjs/wiki) の参照をお願いします

**Comment by tell-k** [comment]
@aytdm これは `assigned`  のラベルがついてますが、もう担当が決まってるということでしょうか。もしまだ決まってないなら、やろうかなと思ってますー。

**Comment by aytdm** [comment]
@tell-k ありがとうございます！自分でしようと思って `assigned ` のラベルをつけていたのですが `
Assignees` の設定をしていませんでした🙊
翻訳していただけるの助かります、ぜひよろしくお願いしますー！！

**Comment by tell-k** [comment]
@aytdm 了解です！ありがとうございます！対応させていただきますー！
