### ISSUE TITLE
[doc] Update configuration-plugins.md

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.docs.nuxtjs#171]
本家のドキュメントに更新がありました :page_facing_up:
Original:https://github.com/nuxt/docs/commit/9a8ae0b41af9be6729660ec953cbe3af8ebda472

**Comment by wanshot** [comment]
翻訳やります:dog:

**Comment by wanshot** [comment]
@inouetakuya @potato4d @aytdm

変更点は以下PRで翻訳いただけてるのでこのIssueはcloseでお願いします。

* https://github.com/nuxt/docs/pull/1406

**Comment by aytdm** [comment]
@wanshot 確認が甘くてすみません🙇クローズします
