### ISSUE TITLE
[doc] 2.7

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.docs.nuxtjs#175]
本家のドキュメントに更新がありました :page_facing_up:
Original:https://github.com/nuxt/docs/commit/6bef701721e55b9190e2f7dc2345f0de3f20c4ff

**Comment by noriaki-yamada** [comment]
`ja/api/configuration-build.md` は https://github.com/nuxt/docs/pull/1390 で対応しています。

**Comment by noliaki** [comment]
`ja/api/configuration-build.md` は https://github.com/nuxt/docs/pull/1390 で対応しています。

**Comment by noliaki** [comment]
やります🙋

**Comment by noliaki** [comment]
en の更新内容は既に日本語に翻訳されているので、こちらは対応不要だと思います。

**Comment by aytdm** [comment]
確かに不要ですね。すみません、確認をありがとうございます。こちらクローズします
