### ISSUE TITLE
@textlint-rule/textlint-rule-no-invalid-control-character 導入の提案

### ISSUE THREAD

**Issue by noliaki** [vuejs-jp/ja.docs.nuxtjs#177]
@inouetakuya @potato4d @aytdm

[@textlint-rule/textlint-rule-no-invalid-control-character](https://github.com/textlint-rule/textlint-rule-no-invalid-control-character) を追加するのはどうでしょう？
不要な制御文字を検出し、`fix` で削除してくれるルールです。

## 経緯
- 既存ファイルで不要な制御文字が混入されているのを発見した
https://github.com/nuxt/docs/blame/master/ja/api/configuration-server.md#L23
- 今後 新規で作成する際にも 不要な制御文字が混入される可能性があると思った
- `` というような意図しない表示になるのではないかと思った

## 期待される効果
- レビュー指摘事項の軽減
- 制御文字による意図しない表示の削減

## 導入方法
1. `@textlint-rule/textlint-rule-no-invalid-control-character` のインストール
`npm install @textlint-rule/textlint-rule-no-invalid-control-character --save-dev`
2. `ja/.textlintrc` ファイル に `"@textlint-rule/no-invalid-control-character": true` を追記
参考: https://github.com/textlint-rule/textlint-rule-no-invalid-control-character#usage

## このIssue の完了条件
- [ ] `@textlint-rule/textlint-rule-no-invalid-control-character` 導入完了
または
- [ ] `@textlint-rule/textlint-rule-no-invalid-control-character` 導入提案の却下

## 影響範囲

こちらで 導入してみて `fix` かけましたが、 制御文字が混入されていたのは `ja/api/configuration-server.md` だけでした…
https://github.com/noliaki/docs/compare/master..add-textlint-rule-no-invalid-control-character

**Comment by potato4d** [comment]
良いと思います :+1:

**Comment by aytdm** [comment]
@noliaki ご提案ありがとうございます！良いですね:+1: PR を作成して頂けないでょうか🙏

**Comment by inouetakuya** [comment]
わたしも賛成です！:+1:

**Comment by noliaki** [comment]
ご確認 ありがとうございます🙇‍♂️
PR作成したので、お手すきのときに ご確認 お願いいたします🙏
