### ISSUE TITLE
en/api/internals-renderer.md の翻訳

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.docs.nuxtjs#18]
https://github.com/nuxt/docs/commit/b000302 の差分を翻訳します。

翻訳の流れは [Nuxt 2.0 ドキュメント翻訳 · Issue #9 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/9) を参照してください。

**Comment by hivesbee** [comment]
@inouetakuya @aytdm 
こちらの issue ですが、以下のプルリクで解決済みだったりしますでしょうか？
[ja: update ja/api/internals-renderer.md #878](https://github.com/nuxt/docs/pull/878)

**Comment by aytdm** [comment]
@hivesbee 
コメントありがとうございます。
ご指摘のとおり、ryota-yamamotoさんが翻訳されてますね･･･！
確認不足ですみません～！本件、翻訳済みでcloseとさせてください:bow:
