### ISSUE TITLE
[doc] en: update extractCSS plugin ref

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.docs.nuxtjs#180]
本家のドキュメントに更新がありました :page_facing_up:
Original:https://github.com/nuxt/docs/commit/8cc565d9f63a4524b15eb8d87a75eacfe469b8f7

**Comment by wanshot** [comment]
翻訳やります:dog:

**Comment by aytdm** [comment]
ありがとうございます！よろしくお願いします
