### ISSUE TITLE
[doc] fix: correctly rename cofiguration-build

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.docs.nuxtjs#182]
本家のドキュメントに更新がありました :page_facing_up:
Original:https://github.com/nuxt/docs/commit/7d0c5a55d61f80a2a708d5de3eddbd40cd8dc435

**Comment by aytdm** [comment]
PR 内容自体の修正は不要だが、 バッククオートが閉じられていないので`` `less-loader`` →  `` `less-loader` ``に修正が必要

**Comment by noliaki** [comment]
やります🙋
