### ISSUE TITLE
更新通知 Bot を開発する

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.docs.nuxtjs#2]
## 要件

1. 定期的に nuxt/docs と同期を取る
2. en/ に更新があった場合は、その旨を Slack に通知する
3. 通知先は vuejs-jp の #translation_notify

**Comment by potato4d** [comment]
Vue.js JP Docs みたいに Issue 化あたりまではやってくれても良いかも

**Comment by inouetakuya** [comment]
@potato4d 

[Nuxt 2.0 ドキュメント翻訳 · Issue #9 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/9) の期間を一旦 11/30（金）までと設定したので、できれば本 Issue の件の開発も 11/30（金）を目途にしたいのですが、どうでしょう？

**Comment by potato4d** [comment]
@inouetakuya OKっす！

**Comment by potato4d** [comment]
@inouetakuya 
こちらなんですが、自分も体調今崩しておりまして、翻訳の引き継ぎはできてもコードを書くのはちょっと頭働いていない状況なので来週くらいまで見てもらえると助かります :bow:

**Comment by inouetakuya** [comment]
承知しました。お大事になさってください〜 🏥

**Comment by potato4d** [comment]
これちょっと遅れましたが今週来週やります。Issueに立てるところまでできればと

**Comment by inouetakuya** [comment]
@potato4d 

多方面でアクションされていて忙しそう... という雰囲気は感じておりますので、少し余裕を持って、今度の 10連休あたりにやっていただければ大丈夫です〜 :relaxed:

**Comment by aytdm** [comment]
[Slack上でアナウンス](https://vuejs-jp.slack.com/archives/C1P227P7V/p1555939817002800)されていたので、こちらクローズしますね
ご対応ありがとうございました

**Comment by potato4d** [comment]
はい〜

**Comment by potato4d** [comment]
遅くなってすみません🙇‍♂️

**Comment by inouetakuya** [comment]
いえいえ〜、対応ありがとうございました！！
