### ISSUE TITLE
en/guide/commands.md の翻訳

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.docs.nuxtjs#26]
https://github.com/nuxt/docs/commit/b000302 の差分を翻訳します。

翻訳の流れは [Nuxt 2.0 ドキュメント翻訳 · Issue #9 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/9) を参照してください。

**Comment by rascate** [comment]
@inouetakuya 
翻訳担当させてください！

**Comment by inouetakuya** [comment]
[ja: Update ja/guide/commands.md by rascate · Pull Request #935 · nuxt/docs](https://github.com/nuxt/docs/pull/935)
