### ISSUE TITLE
en/guide/contribution-guide.md の翻訳

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.docs.nuxtjs#28]
https://github.com/nuxt/docs/commit/b000302 の差分を翻訳します。

翻訳の流れは [Nuxt 2.0 ドキュメント翻訳 · Issue #9 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/9) を参照してください。

**Comment by aytdm** [comment]
https://github.com/nuxt/docs/pull/1015 で翻訳済み

Close https://github.com/nuxt/docs/pull/1015
