### ISSUE TITLE
トップページの翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.docs.nuxtjs#36]
https://ja.nuxtjs.org/ 
トップページがリニューアルされましたね！こちらも翻訳していきましょう！

**Comment by potato4d** [comment]
@inouetakuya @aytdm 
ひとまず自分が持ちますが、土日でできなかったらパスするかもです！

**Comment by inouetakuya** [comment]
@potato4d 

https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/37#issuecomment-468592903

一旦、差分チェック Bot の開発に専念していただきたいので、アサインを外しますねー 😄

**Comment by yoshimuraK** [comment]
@53able @tiwuofficial @kuromoka
GameWithのエンジニアがやります！

**Comment by aytdm** [comment]
トップページの文章、ハードコーディングされているので まずは本体の作りを変えないといけない気がしています:thinking:

**Comment by kuromoka** [comment]
@aytdm 
ハードコーティングされてしまっているのは本体リポジトリのこのあたりですかね 🤔 
https://github.com/nuxt/nuxtjs.org/tree/master/partials/home
この場合どのように対応したらよろしいでしょうか？

**Comment by aytdm** [comment]
そうですね。上でも書いたように md ファイルを読み込んで表示するような作りに変えてあげないと訳せないですね

**Comment by 53able** [comment]
@aytdm 

現状のTOPページを見たところ、 `Nuxt.js をオンラインで試す` が表示されています。

該当する箇所は、https://github.com/nuxt/nuxtjs.org/blob/master/partials/home/codesandbox.vue#L4 の様です。 日本語訳は、 https://github.com/nuxt/docs/blob/master/ja/lang.json#L43 だと考えられます。

この感じだと、ハードコーディングされているドキュメントを、`$store.state.lang.homepage.xxx` に置き換えていく必要がありそうです。

https://github.com/nuxt/nuxtjs.org/tree/master/partials/home 配下の `.vue` を修正することになりそうですが、どうしましょうかねー 🤔

**Comment by nayuta** [comment]
はじめまして！
こちらちょっと気になっているので見ているのですが、どなたか取り組んでいらっしゃる方はいますか？

**Comment by aytdm** [comment]
@nayuta 初めまして。翻訳できるようにするところまでを私の方でようやく見始めたところです。
翻訳自体は手をあげてくださっているお三方にお願いしようと思っていますが、ご興味ありますか？

**Comment by nayuta** [comment]
@aytdm こんにちは。私が興味があったのは本体側です。もう取り組んでいらっしゃるのであればそれで！

**Comment by aytdm** [comment]
@nayuta あ、興味があるか聞いたのは本体の方です。言葉足らずでしたね:bow:
もしやりたいのであれば取り組んでもらって構いません。（その場合、3月下旬までを目途にしていただけると助かります）

**Comment by nayuta** [comment]
@aytdm すみません。そのまま進めてしまいコメントの修正を先程見ました。先にコメントつけておけばよかったです。一旦こちらで完了しましたが、その後いかがでしょうか？（１つ出ればいいと思うので。。。）

**Comment by aytdm** [comment]
@nayuta そうなんですね。完了したのであれば nayuta さんの方で PR をお願いします。

**Comment by 53able** [comment]
@aytdm 
 翻訳の作業は、 @nayuta さんのPRがマージされ次第取り掛かろうと思います!
CC: @tiwuofficial @kuromoka @yoshimuraK

**Comment by nayuta** [comment]
@aytdm アドバイスを頂きたいのですが、これは各PRに `ja: ` をつけたほうがいいでしょうか？

**Comment by aytdm** [comment]
@nayuta PR ありがとうございます！`ja` に限ったものではないのでつけなくて大丈夫です〜

**Comment by nayuta** [comment]
@aytdm ありがとうございます。 /nuxt/nuxtjs.org/issues/178 に issue を立てています。進んだらまたここに報告しますね。

**Comment by nayuta** [comment]
まだ deploy はされていないようですが、 PR が master に merge されたようなのでお知らせします。

README.md にも修正を入れるべきだったのですが、トップページのドキュメントは [/nuxt/docs/tree/master/en/homepage] から fallback するようになっているため、各言語の翻訳者の方が .md ファイルをコピーする必要があります。（ PR でミスがあって一部の言語でトップページの一部が欠けてしまうのを防ぐため。 PR の目的が top page の翻訳なので、 api や lang.json については既存の仕様のままとなっています。）

Discord にアカウントが作れず、他の言語の翻訳者の方に連絡が取れないのですが、もし可能ならお知らせいただけるとありがたいです。

**Comment by aytdm** [comment]
@nayuta cc: @inouetakuya  遅くなりましたが、ご対応ありがとうございました！
申し訳ありませんが、他言語の翻訳者の方への連絡手段を持っておらず...メンテナンス状況も不明なのでひとまず `ja` のみ進めようと思います。

@53able @tiwuofficial @kuromoka @yoshimuraK
遅くなりましたが、nayuta さんが対応してくださったので翻訳できる状態になりました。
対応が必要なのは以下のファイルになります。

+ [ ] homepage\backers.md
+ [ ] homepage\modes.md
+ [ ] homepage\modes_server_side_rendering.md
+ [ ] homepage\modes_single_page_app.md
+ [ ] homepage\modes_statically_generated.md
+ [ ] homepage\welcome.md
+ [ ] homepage\welcome_figure.md
+ [ ] homepage\why.md
+ [ ] homepage\why_enjoyable.md
+ [ ] homepage\why_modular.md
+ [ ] homepage\why_performant.md
+ [ ] lang.json

数が多いので他の方へも声をかけようと思いますが、まずは手をあげてくださった4人で担当可能なファイルを決めていただけないでしょうか？残ったものを募集しようと思います。

**Comment by 53able** [comment]
@aytdm ありがとうございます!
本日、こちらで担当を割り振りたいと思います!

**Comment by 53able** [comment]
@aytdm 
次の8点は、 @53able 担当で大丈夫です!

- [ ] homepage\modes.md
- [ ] homepage\modes_server_side_rendering.md
- [ ] homepage\modes_single_page_app.md
- [ ] homepage\modes_statically_generated.md
- [ ]  homepage\backers.md
- [ ] homepage\welcome.md
- [ ] homepage\welcome_figure.md
- [ ] lang.json

もしかしたら、いくつかを @tiwuofficial @yoshimuraK にかえるかもしれません。

**Comment by kuromoka** [comment]
@aytdm
以下のファイルについては、私で対応します！
- homepage\why.md
- homepage\why_enjoyable.md
- homepage\why_modular.md
- homepage\why_performant.md

**Comment by tiwuofficial** [comment]
@aytdm 
こちらは自分が対応します！

- homepage\modes_server_side_rendering.md
- homepage\modes_single_page_app.md
- homepage\modes_statically_generated.md

**Comment by aytdm** [comment]
@53able @kuromoka @tiwuofficial ありがとうございます。よろしくお願いします！ （いつでも分担しますので、対応が難しい際は遠慮なく仰ってください）

**Comment by 53able** [comment]
@aytdm 
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/36#issuecomment-478805271 
に関してのPRは全て発行出来たと思います😅

**Comment by aytdm** [comment]
@53able @tiwuofficial もろもろご対応ありがとうございます。遅くなりましたが頂いた PR についてレビューしました。
`homepage\modes_statically_generated.md` は PR が出ていない認識です。良ければ私の方で対応しましょうか？

**Comment by 53able** [comment]
@aytdm 
すみません!
漏れていました…

@yoshimuraK が `homepage\modes_statically_generated.md` のPRを出します!

**Comment by aytdm** [comment]
@53able ありがとうございます🙇

**Comment by tiwuofficial** [comment]
@aytdm @53able @yoshimuraK すみません！対応ありがとうございます！！！

**Comment by aytdm** [comment]
@53able @tiwuofficial @kuromoka @yoshimuraK cc: @inouetakuya 
トップページ、全て翻訳完了しました。連休前の忙しい中、ご対応ありがとうございました:tada::tada::tada:
