### ISSUE TITLE
ドキュメント翻訳 2019 春の陣

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.docs.nuxtjs#37]
Nuxt 2.0 ドキュメント翻訳のメンバーにメンション。

@potato4d @aytdm @resessh @rascate @shika358 @ry0-ta @watkazuki @teinen @hivesbee @53able @tell-k @ymmooot @ryamakuchi @MozyOk

Nuxt 2.0 ドキュメント翻訳が終わってから、en との差分がだいぶ発生してしまったので、ここいらでガッツリ翻訳していきましょう！:muscle:

## 一緒にやっていきたい人！

この Issue にその旨をコメントしてください！:pray:

（コメントをすると、自動的にこの Issue を subscribe するようになります）

今後の案内等はこの Issue にコメントするかたちで行います。

## スケジュール

- [x] 一緒にやっていく人を募る（3/1 金） @inouetakuya
- [x] GitHub プロジェクトを作成する（3/1 金） @inouetakuya
- [x] 翻訳対象ファイルについて、1ファイル 1Issue 立てて、GitHub プロジェクトに結び付ける（3/3 日） @aytdm 
- [x] 翻訳する（3/3 日 〜 3/31 日）

## 翻訳の流れ

よく分からない点がありましたら、この Issue でカジュアルに質問してください〜 :smile:

### 翻訳する人

(1) GitHub プロジェクト（ https://github.com/vuejs-jp/ja.docs.nuxtjs/projects/2 ）を開いて **「未アサイン」となっている Issue** を選んで、**自分が翻訳を担当する旨を当該未アサイン Issue 内にコメント**する
(2) `nuxt/docs` リポジトリを各自 Fork してください
(3) 翻訳して `nuxt/docs:master` ブランチに対してプルリクを出す

- プルリクタイトルに `ja: ` というプレフィックスを付けてください
- まだ翻訳作業途中のときは `[WIP] ja: ` を付けてください
- プルリク冒頭で @inouetakuya @potato4d @aytdm に対してメンションを飛ばしてください
- コメント等は、英語で表現するのが難しいケースもあると思うので、必ずしも無理して英語でする必要はありません

### レビューする人（@inouetakuya @potato4d @aytdm 以外もお願いします）

(4) `nuxt/docs` 内の日本語翻訳プルリクをレビューする。マージして問題なさそうだと思ったらその旨をコメントする

### マージする人（@inouetakuya @potato4d @aytdm）

(5) マージしてよい状態になったプルリクをマージする
(6) https://github.com/vuejs-jp/ja.docs.nuxtjs/projects/2 内の Issue をクローズする（= 自動的に「Done」に移動される）

## 翻訳対象ファイル一覧

```shell
git diff b000302bd83a2bef8c00979c98ab1c2d62f2dcb0..e53272a68e3a4ac45373ec333b14009f45dbf29b --stat en/ | pbcopy
```

```text
 en/api/components-no-ssr.md               |   2 -
 en/api/components-nuxt-child.md           |  34 +++++
 en/api/components-nuxt-link.md            |   7 +-
 en/api/components-nuxt.md                 |   7 +
 en/api/configuration-build.md             | 211 ++++++++++++++++++++++--------
 en/api/configuration-builddir.md          |   2 +-
 en/api/configuration-css.md               |   2 +-
 en/api/configuration-dev.md               |   8 +-
 en/api/configuration-dir.md               |   2 +-
 en/api/configuration-env.md               |  12 +-
 en/api/configuration-generate.md          |  45 ++-----
 en/api/configuration-global-name.md       |  42 ++++++
 en/api/configuration-head.md              |  15 ++-
 en/api/configuration-hooks.md             | 113 ++++++++++++++++
 en/api/configuration-ignore.md            |   2 +-
 en/api/configuration-loading-indicator.md |  16 +--
 en/api/configuration-loading.md           |  28 +++-
 en/api/configuration-modern.md            |  34 +++++
 en/api/configuration-modules.md           |   2 +-
 en/api/configuration-modulesdir.md        |  12 +-
 en/api/configuration-plugins.md           |   2 +-
 en/api/configuration-render.md            |  41 +++++-
 en/api/configuration-rootdir.md           |   6 +-
 en/api/configuration-router.md            |  26 ++--
 en/api/configuration-servermiddleware.md  |  10 +-
 en/api/configuration-srcdir.md            |   2 +-
 en/api/configuration-transition.md        |   6 +-
 en/api/configuration-vue-config.md        |   4 +-
 en/api/context.md                         |  28 ++--
 en/api/index.md                           |  19 ++-
 en/api/internals-builder.md               |   6 +-
 en/api/internals-generator.md             |   2 +-
 en/api/internals-module-container.md      |  10 +-
 en/api/internals-nuxt.md                  |   2 +-
 en/api/internals-renderer.md              |   8 +-
 en/api/internals.md                       |  18 +--
 en/api/menu.json                          |  37 +++++-
 en/api/nuxt-render-and-get-window.md      |   6 +-
 en/api/nuxt-render-route.md               |   8 +-
 en/api/nuxt-render.md                     |  10 +-
 en/api/pages-fetch.md                     |  10 +-
 en/api/pages-head.md                      |   7 +-
 en/api/pages-loading.md                   |  28 ++++
 en/api/pages-scrolltotop.md               |   4 +-
 en/api/pages-validate.md                  |   2 +-
 en/api/pages-watchquery.md                |   4 +-
 en/examples/auth-external-jwt.md          |  56 ++++++--
 en/examples/auth-routes.md                |   8 +-
 en/examples/i18n.md                       |   4 +
 en/examples/named-views.md                |   7 +
 en/faq/appengine-deployment.md            |  59 +++++++++
 en/faq/deployment-aws-s3-cloudfront.md    |  95 +++++++++-----
 en/faq/duplicated-meta-tags.md            |   6 +-
 en/faq/extend-webpack.md                  |   2 +-
 en/faq/external-resources.md              |   4 +-
 en/faq/github-pages.md                    |  10 +-
 en/faq/google-analytics.md                |   8 +-
 en/faq/heroku-deployment.md               |  14 ++
 en/faq/host-port.md                       |  12 +-
 en/faq/http-proxy.md                      |  29 ++++
 en/faq/ios-phone-numbers.md               |  21 +++
 en/faq/jsx.md                             |   8 +-
 en/faq/menu.json                          |   7 +-
 en/faq/netlify-deployment.md              |   6 +-
 en/faq/nginx-proxy.md                     |  86 +++++++++++-
 en/faq/now-deployment.md                  |  34 +++++
 en/faq/postcss-plugins.md                 |  24 +++-
 en/faq/pre-processors.md                  |   2 +-
 en/faq/surge-deployment.md                |   6 +-
 en/faq/webpack-plugins.md                 |   4 +-
 en/faq/window-document-undefined.md       |  12 +-
 en/guide/assets.md                        |  47 ++++---
 en/guide/async-data.md                    | 104 +++++++++------
 en/guide/commands.md                      |  31 +++--
 en/guide/configuration.md                 |  42 +++---
 en/guide/contribution-guide.md            | 105 ++++++++++++++-
 en/guide/development-tools.md             |  10 +-
 en/guide/directory-structure.md           |  30 +++--
 en/guide/index.md                         |  25 +++-
 en/guide/installation.md                  |  43 +++++-
 en/guide/menu.json                        |   5 +-
 en/guide/modules.md                       | 188 ++++++++++++++++----------
 en/guide/plugins.md                       |  70 ++++------
 en/guide/routing.md                       | 124 +++++++++++++++---
 en/guide/views.md                         | 147 ++++++++++++---------
 en/guide/vuex-store.md                    | 104 +++++++--------
 en/lang.json                              |  14 +-
 87 files changed, 1831 insertions(+), 684 deletions(-)
```

## 翻訳対象（差分）

```
git diff b000302bd83a2bef8c00979c98ab1c2d62f2dcb0..e53272a68e3a4ac45373ec333b14009f45dbf29b en/ | pbcopy
```

差分内にMarkdown 記法を使われている箇所があるため、Issue コメントとして貼ると表示が崩れてしまったため、Gist に貼りました。

Nuxt 公式ドキュメント翻訳 2019 春の陣の翻訳対象
https://gist.github.com/inouetakuya/4b231c5e634e5e7d0f80856d3eb3691d

一応上記 Gist に貼っていますが、めっちゃ長いので、ひとつのファイルについて差分を見たいときは、下記のようにするのが良さそうです。

```shell
git diff b000302bd83a2bef8c00979c98ab1c2d62f2dcb0..e53272a68e3a4ac45373ec333b14009f45dbf29b en/TARGET_FILE.md
```

**Comment by ymmooot** [comment]
💪

**Comment by tell-k** [comment]
✋

**Comment by RyoNkmr** [comment]
やりたいです！

**Comment by wanshot** [comment]
翻訳メンバーではないですが、新たに参加したいです。

**Comment by ryamakuchi** [comment]
参加します！

**Comment by sunecosuri** [comment]
参加したいですー！

**Comment by mtmtkzm** [comment]
2.0 参加していませんが、参加したいです 💪

**Comment by aytdm** [comment]
@inouetakuya ありがとうございます！

> 翻訳対象ファイルについて、1ファイル 1Issue 立てて、GitHub プロジェクトに結び付ける（3/3 日） 

いろいろ抱えていらっしゃるのでこちら担当します

**Comment by moksahero** [comment]
やります！

**Comment by doutori** [comment]
翻訳メンバーではなかったですが、お手伝いさせてください〜

**Comment by potato4d** [comment]
@inouetakuya 

ちょっと後々になってしまっている Bot を動かして翻訳環境に載せるところをやりきりたいので、今回はレビューに専念させてください :pray:

ちょうど差分チェックして Issue 立てたりやっていくのにもベストな時期な気がするので、ちょっとこっちやりきりますー

**Comment by ryuhei4k9** [comment]
参加させてください！

**Comment by 448jp** [comment]
参加希望です 🙌

**Comment by resessh** [comment]
💪

**Comment by inouetakuya** [comment]
@aytdm

https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/37#issuecomment-468591010

めちゃくちゃ助かります！！お願いします！！！:pray:

**Comment by inouetakuya** [comment]
@potato4d 

https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/37#issuecomment-468592903

うおお！！助かります！！よろしくお願いします！！！:pray:

**Comment by aytdm** [comment]
@potato4d ありがとうございます！助かります〜！！
1点確認で、試されるようなら issue立ては待ってた方がいいでしょうか？立てても問題なければこちらで立ててしまいます:muscle:

**Comment by shika358** [comment]
もちろんやりますよ～

**Comment by hivesbee** [comment]
やりたいですー！

**Comment by aytdm** [comment]
@potato4d 考えたら足並みを揃えなくてもそれぞれ進められるので、こちらはこちらで進めますー

**Comment by aytdm** [comment]
@resessh @RyoNkmr @shika358 @hivesbee @tell-k @ymmooot @ryamakuchi @wanshot @448jp @ryuhei4k9 @doutori @moksahero @sunecosuri @mtmtkzm 
cc: @inouetakuya 

issue 立て完了しましたので、お手すきの際に担当したい issue にコメントをお願いします:pray:
（確認したつもりですが、もし何か表記ミスがあったらすみません）

ボリュームがありますが、やっていきましょー！！:muscle:

**Comment by inouetakuya** [comment]
Issue 立てにもクオリティってたしかに出るんだなと思った。流石過ぎる。

![gmrmcmrln](https://user-images.githubusercontent.com/634357/53678961-64674400-3d09-11e9-84c8-1e3895402d3b.jpg)

**Comment by hisako135** [comment]
出遅れましたがやります！

**Comment by 53able** [comment]
やります!
貢献したいです!
今回は、しっかり時間を確保します!!

**Comment by tiwuofficial** [comment]
やります！！！

**Comment by kuromoka** [comment]
ぜひやりたいです！

**Comment by yoshimuraK** [comment]
やります！

**Comment by aytdm** [comment]
翻訳対象の中ですでに翻訳済みのため翻訳不要なファイルがいくつかありました。確認が甘くすみません:bow:

除いたつもりですが、もしこれから担当するものが対応不要そうな場合コメントで教えていただけると助かります:pray:

**Comment by serima** [comment]
やりたいです！

**Comment by yahsan2** [comment]
参加します。

**Comment by inouetakuya** [comment]
`@here`

[型の表記を en/ に合わせて Boolean / Object など英語表記で統一する · Issue #126 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/126)

という Issue を追加しました。やっていただける勇者を募集しています 🙏

**Comment by aytdm** [comment]
気づけば未アサインの issue も残すところあと１つとなりました！:tada: みなさまありがとうございます！！
あともう少し、引き続きよろしくお願いしますー😄

**Comment by aytdm** [comment]
こちらにコメントしており取り組んだ issue がまだない方で、以下のいずれかをやってみたいという方いませんか？
+ #99 en/api/configuration-modulesdir.md
+ #88 en/api/configuration-dir.md
+ #84 en/api/configuration-build.md

翻訳というよりはコード例の修正など軽微な修正対応になります。

翻訳ではないから巻き取るつもりでしたが、せっかく意思表明されているので良ければぜひ🙌
**3/22まで**にコメントがなければこちらでPRを作ります～

**Comment by 53able** [comment]
今回は、打ち上げ🍺とか、やらないんですか??

**Comment by inouetakuya** [comment]
すみません、今回、わたしのほうではやる予定ないです 🙏 

（どなたかが音頭をとっていただいて、やっていただく分には全く問題ありません）

**Comment by aytdm** [comment]
春の陣、無事に完了しました:tada::tada::tada: いつも翻訳に参加してくださっている方はもちろん、今回初めて翻訳に参加してくださった方もご協力本当にありがとうございました！！
ガイドラインの整備など課題もありますが、Botも動き始めたのでこれまでよりメンテしやすくなると思います（Thanks potatp4d！）。
良い日本語ドキュメントを提供できるよう、引き続きよろしくお願いします:pray:
