### ISSUE TITLE
en/guide/installation.md の翻訳

### ISSUE THREAD

**Issue by aytdm** [vuejs-jp/ja.docs.nuxtjs#47]
### 翻訳対象

/guide/installation.md
https://github.com/nuxt/docs/commit/e53272a との差分を翻訳します。
詳細な差分は `git diff` コマンドで見るか、いのうえさんが用意してくださった[こちらの gist](e53272a) を参照してください。

### 翻訳の流れ

まずはこの issue にコメントで翻訳する意思表示をお願いします🙋
それ以降の流れは [#37ドキュメント翻訳 2019 春の陣](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/37#issue-415991098) を参照してください。

### 翻訳スタイル

Vue.js に合わせています。
スタイルについては[こちら](https://github.com/vuejs-jp/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md#%E7%BF%BB%E8%A8%B3%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB)を参照してください。

**Comment by sunecosuri** [comment]
こちらも対応しますー 🙋‍♂️

**Comment by sunecosuri** [comment]
> nuxt@e53272a との差分を翻訳します。

@aytdm さんが立てていただいたissue のリンク先(正しくはコミットハッシュ)がおそらくすべて同一のものになっていましたので、念の為ご報告しますー `en/guide/installation.md`

**Comment by aytdm** [comment]
@sunecosuri 確かにこれは適切じゃないですね... :bow:
ファイル毎でコミット間の diff が出せないので、どうかなと思ったのですがコミット間の diff を表示するリンクに更新します。ご指摘ありがとうございます！
