### ISSUE TITLE
ドキュメント翻訳 2018 秋の陣

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.docs.nuxtjs#5]
@potato4d @aytdm @shika358（とりあえず Nuxt っぽい人にメンション）

Nuxt 2.0 がいつリリースされてもおかしくないし、その前にガッとやっちゃうよ！やっていきましょうー！:muscle:

## 一緒にやってくれる人！

この Issue にその旨をコメントしてください！:pray:

（コメントをすると、自動的にこの Issue を subscribe するようになります）

今後の案内等はこの Issue にコメントするかたちで行います。

## スケジュール

* [x] 翻訳対象ページの一覧作成（9/7 金） @inouetakuya
  * Google スプレッドシート
* [x] 一緒にやっていく人を募る 9/7 金 〜
* [x] 翻訳する 9/7 金 〜 10/8（月）

## 翻訳対象ファイル一覧

* https://docs.google.com/spreadsheets/d/1fj41JP8nhRknwvaUuBDDXiRjxACRfHBxY63v--tcNMI/edit?usp=sharing

## 翻訳の流れ

よく分からない点がありましたら、この Issue でカジュアルに質問してください〜 😄

### 翻訳する人

(1) 下記 Google スプレッドシートを開く
(2) 翻訳するファイルを選んで **「翻訳する人」に自分の GitHub アカウントを書く**
(3) `nuxt/docs` リポジトリを各自 Fork してください
(4) 翻訳して `nuxt/docs:master` ブランチに対してプルリクを出す

* プルリクタイトルに `ja: ` というプレフィックスを付けてください
* まだ翻訳作業の途中のときは `[WIP] ja:` を付けてください
* コメント等は、英語で表現するのが難しいケースもあると思うので、必ずしも無理して英語でする必要はありません

(5) スプレッドシート内の **「nuxt/docs へプルリクを出した」にチェックを入れる**

### レビューする人（@inoutakuya @potato4d @aytdm 以外もお願いします）

(6) `nuxt/docs` 内の日本語翻訳プルリクをレビューする。マージして問題なさそうだと思ったらその旨をコメントする

### マージする人（@inoutakuya @potato4d @aytdm ）

(7) マージしてよい状態になったプルリクをマージする

## FAQ

随時足していきます。

### あれ？ja.docs.nuxtjs は使わないのですか？

ja.docs.nuxtjs は Issue 管理のリポジトリとして使うことにしました。

理由）ja.docs.nuxtjs 内で翻訳プルリク作業を行ってから本家 nuxt/docs へプルリクを出す方式だと、（nuxt/docs では squash merge を採用しており）翻訳してくれた人が nuxt/docs の contributors に記録されないため。

### ファイルのどこの部分の訳が足りないのか分かりづらいです

うーん、現時点では https://gitlocalize.com/repo/100/ja/en を見るのもひとつの手かもです。

**Comment by potato4d** [comment]
やります！

**Comment by aytdm** [comment]
一覧作成ありがとうございます！
やります〜

以下、お願いと確認になります。

（1）レビューのお願い（on Gitlocalize）
以前Gitlocalizeにレビューリクエストしたものが残っていました。
お手すきの際に確認頂けると助かります:bowing_man:
https://gitlocalize.com/repo/100/ja/review/5538
https://gitlocalize.com/repo/100/ja/review/6825

（2）Gitlocalize上で翻訳したものの、レビューリクエストが出せない件の扱いにいついて
Gitlocalize上のチャットから再度リクエストを出すようにできないか確認しています。
返答内容次第ですが、もしできない場合は再翻訳する方向で問題ないでしょうか？
https://gitlocalize.com/repo/100/ja/review/672

**Comment by inouetakuya** [comment]
@aytdm 

ありがとうございます！

> https://gitlocalize.com/repo/100/ja/review/5538
> https://gitlocalize.com/repo/100/ja/review/6825

こちらについては、レビュー＆本家へ反映終わりましたー

**Comment by resessh** [comment]
やります！ 🙋‍♀️

**Comment by shika358** [comment]
やりますー

**Comment by ryamakuchi** [comment]
やらせてください！:pray:

**Comment by ryota-yamamoto** [comment]
やりたいです！

**Comment by aytdm** [comment]
スプレッドシートを確認したところ、Gitlocalize上のステータスと実際のステータスが
乖離（未翻訳が100%になっている/100%ではないが翻訳が完了している）していたので修正しました。
＃inoue さんには連絡済みです

具体的には以下のファイルのステータスを変更しました。
(1) 翻訳対象に変更
```
【example】
auth-external-jwt.md 100%
```

(2) 翻訳不要対象に変更
```
【api】
components-no-ssr.md 91%
configuration-builddir.md 88%
configuration-css.md 72%
configuration-dir.md 100%
configuration-loading-indicator.md 80%
configuration-plugins.md 93%
configuration-rootdir.md 66%
nuxt-render.md
nuxt.md 76%
pages-fetch.md 94%
pages-middleware.md Conflict
pages-scrolltotop.md 50%
pages-transition.md 85%

【faq】
cached-components.md 84%
duplicated-meta-tags.md 81%
jsx.md 75%
```

@inouetakuya 
> 翻訳する 9/7 金 〜

なので、翻訳するファイルをアサインし始めて大丈夫ですよね:muscle:

先日コメントに記載したGitlocalizeの件は先方が調査してくださっています。
返信があり次第、こちらに記載します〜

**Comment by inouetakuya** [comment]
ありがとうございました！！めちゃくちゃ助かります！！

> なので、翻訳するファイルをアサインし始めて大丈夫ですよね💪

はい！僕のほうも翻訳開始して行きますー :muscle::muscle:

**Comment by inouetakuya** [comment]
他の皆さんも Issue 冒頭の「翻訳の流れ」に沿って、作業はじめちゃってくださいー 🙏

**Comment by potato4d** [comment]
やっていきましょう！

**Comment by 53able** [comment]
やりたいです!

**Comment by MozyOk** [comment]
自分も参戦したいっす!

**Comment by tell-k** [comment]
@inouetakuya 先ほど一つPRを出してみましたー。

https://github.com/nuxt/docs/pull/752


> (4) 翻訳して nuxt/docs:master ブランチに対してプルリクを出す（Reviewers に @inoutakuya @potato4d を指定してください）

PRを出して 一点気づいたのですが、どうやら権限がないので 私には Reviewers にお二人を追加できないようでした。(多分そのようにリポジトリが設定されてるのかもです)

<img width="294" alt="reviewers" src="https://user-images.githubusercontent.com/26263/45401291-ef388180-b68a-11e8-9b11-a119ca7f721d.png">
(歯車アイコン的なものが出てこないです)

もしReviewersを設定するために、何か手順などがあれば教えてもらえると助かります。

**Comment by inouetakuya** [comment]
@tell-k 

> PRを出して 一点気づいたのですが、どうやら権限がないので 私には Reviewers にお二人を追加できないようでした。(多分そのようにリポジトリが設定されてるのかもです)

なるほど、確認しますー（共有ありがとうございます！

**Comment by potato4d** [comment]
レビュアー、PR送信者が無闇に触れないのが正しい挙動だったはずなので、PRに prefix ja: などをつけてもらうほうが良いかもしれませんねー

**Comment by inouetakuya** [comment]
@みなさん

＼(^O^)／ 初マージだ！

* [Update ja/api/configuration-ignore.md by tell-k · Pull Request #752 · nuxt/docs](https://github.com/nuxt/docs/pull/752#pullrequestreview-154498305)

Issue 冒頭にも書きましたが、プルリクの中のやりとりのなかで「これ英語で伝えるの難しいわー」という箇所も出てくるかと思うので、無理して英語にしなくてもよい運用にしようと考えています（そもそも日本語の表現について、英語オンリーでは無理がある）

**Comment by rascate** [comment]
@inouetakuya 
先ほどPRを出させて頂きました。
https://github.com/nuxt/docs/pull/753

よろしくお願いします m( _ _)m

**Comment by potato4d** [comment]
@inouetakuya 
スプレッドシートだと記入漏れとかがあるので次からIssueをバスバス立ててしまってそっちでアサインしていくほうが良さそうですね〜

**Comment by inouetakuya** [comment]
いいすね。それなら GitHub の project 機能も使えますね。次回はそれで行きましょうー（きっと Nuxt 2.0 のタイミングで使うことになるはず）

**Comment by inouetakuya** [comment]
@aytdm (numa）さんが無事に Japanese primary maintainer(s) になったので、それにあわせて Issue 冒頭を編集しましたー :tada:

* [Add numa(aytdm) to Japanese primary maintainer(s) by inouetakuya · Pull Request #747 · nuxt/docs](https://github.com/nuxt/docs/pull/747)

**Comment by aytdm** [comment]
@inouetakuya

ありがとうございます！
引き続きよろしくお願いします

**Comment by ryamakuchi** [comment]
@inouetakuya 
お疲れさまです。さきほどPRをひとつ出しました!

[nuxt#759](https://github.com/nuxt/docs/pull/759)

よろしくお願いします!!

**Comment by potato4d** [comment]
@ryamakuchi 
レビューして変更依頼だしました〜（コロコロ変わっててすみません 🙇 ）。
見ていただけると！

**Comment by inouetakuya** [comment]
### 🍺 打ち上げのご案内 🍺 

皆さん、おつかれさまでしす！いよいよ大詰めですね！

Nuxt 2.0 のドキュメント差分は、きっとドーンと出てくると思いますが、一旦ここらで打ち上げしましょう！

オフラインでお会いしたことない人もいらっしゃるので（というかほとんどがそう）、楽しみです！

場所は新宿か渋谷あたりの居酒屋を考えています。

希望もしくは食べられないものがあれば、コメント欄に書いていただけると〜 :pray:

### 参加希望者は、調整さんに入れてくださいー

Nuxt ドキュメント翻訳 2018 秋の陣 打ち上げ！ | 調整さん
https://chouseisan.com/s?h=2492847d40b941c1b27984de3300ec18

※10/9（火）22時の時点で、サクッと日程を決めちゃいます（それまでに入れてください〜 :pray:

**Comment by aytdm** [comment]
打ち上げいいですね:beers:

翻訳、なかなか進まずすみません:bow:
2.0 で再修正になるかもですが、アサインしているものは連休で終わらせる予定です

**Comment by inouetakuya** [comment]
@potato4d @ryamakuchi @hisako135 @aytdm @shika358 

https://chouseisan.com/s?h=2492847d40b941c1b27984de3300ec18

![image](https://user-images.githubusercontent.com/634357/46712664-1cc61a00-cc8d-11e8-8b0c-e0190f4d8ec6.png)

調整さん登録ありがとうございます！

### 日にち決定 :tada:

* 10/22（月）19:30 〜

に決まりましたので，よろしくお願いします！

### 連絡チャンネル

* vuejs-jp.slack.com に `#181022-nuxt-party` というチャンネルを作りましたので、以降のやり取りはそこで行います〜

**Comment by inouetakuya** [comment]
@53able @potato4d @tell-k @resessh @ryota-yamamoto @ryamakuchi

まだ翻訳残りがあるメンバーにメンションしています！

あと一息です！下記の aytdm さんのプルリク差分を見て勇気をもらいましょうー（まじすごい。正直 1ファイルにこんなに書かれているとは私も知らなかったですw）

* https://github.com/nuxt/docs/pull/833/files

**Comment by inouetakuya** [comment]
@53able @resessh @tell-k @potato4d

そろそろ、このプロジェクトも終わらせたいと思いますので、もし翻訳の時間が取れなさそうでしたら、いま Google スプレッドシート上で翻訳するつもりになっているファイルを手放しても大丈夫ですよー？:smile:

一旦、次の週末まで待ってから、10/29（月）くらいから巻き取って行こうと考えています〜

**Comment by potato4d** [comment]
@inouetakuya 自分はやりますー！

**Comment by tell-k** [comment]
@inouetakuya 私も残りの分を、今日の夜くらい終わらせますー

**Comment by tell-k** [comment]
@inouetakuya @potato4d @aytdm 

質問させてください。

なんとなく 現状の `master` ブランチ で `en` ディレクトリ と `ja` ディレクトリのファイルの差分をとってみました。 

結果 SpreadSheet にも載ってない 且つ  `en` ディレクトリにしか存在しないファイルが 以下のように4つほど見つかりました。

https://github.com/nuxt/docs/tree/master/en/api/configuration-global-name.md
 - 2018/10/16 追加
 - https://github.com/nuxt/docs/pull/869

https://github.com/nuxt/docs/tree/master/en/api/configuration-hooks.md
 - 2018/08/20 追加
 - nuxt:2.0 ブランチにマージ
 - https://github.com/nuxt/docs/pull/716

https://github.com/nuxt/docs/tree/master/en/api/configuration-server.md
 - 2018/08/14 追加
 - nuxt:2.0 ブランチにマージ
 - https://github.com/nuxt/docs/pull/700

https://github.com/nuxt/docs/tree/master/en/faq/deployment-aws-s3-cloudfront.md
 - 2018/08/12 追加
 - nuxt:2.0 ブランチにマージ
 - https://github.com/nuxt/docs/pull/700

これらはのファイルは 2.0 リリース以降のドキュメントっぽいので、今回の翻訳対象からは除外してOKという認識であってますか。

もし対応が必要とかであれば、またどこかで対応しますので教えてくださいー

**Comment by aytdm** [comment]
@tell-k 
一度秋の陣に区切りをつけた後、2.0翻訳プロジェクトを立ち上げる予定なので今回は除外してOKです〜
調査してくださってありがとうございます！
また2.0プロジェクトが始まった際にぜひ一緒にやっていきましょう:+1:

@inouetakuya @potato4d 
それで大丈夫ですよね？（念のため）
＃実は私がレビューの際に2.0対応して頂いたドキュメントが一部あります:bow: すみません。

**Comment by tell-k** [comment]
@aytdm  了解しました！ありがとうございます  👍

**Comment by tell-k** [comment]
@inouetakuya @potato4d @aytdm  

先日出したPRが、なぜか他の人(nuxtの作者)にマージされてしまいましたが、レビューしていただき修正点があれば、別PRで修正しますー。

https://github.com/nuxt/docs/pull/900

**Comment by inouetakuya** [comment]
@tell-k 見ました〜 LGTM ですー 😄 

https://github.com/nuxt/docs/pull/900#issuecomment-432892515

**Comment by tell-k** [comment]
@inouetakuya ありがとうございますー！

**Comment by inouetakuya** [comment]
@tell-k CC: @aytdm 

https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/5#issuecomment-432220620 ありがとうございました！下記でファイル追加対応しました（翻訳は Nuxt 2.0 翻訳プロジェクトにて行います〜）

* [ja: Add files to ja without translation by inouetakuya · Pull Request #922 · nuxt/docs](https://github.com/nuxt/docs/pull/922)

**Comment by 53able** [comment]
@inouetakuya 

> @53able @resessh @tell-k @potato4d
> 
> そろそろ、このプロジェクトも終わらせたいと思いますので、もし翻訳の時間が取れなさそうでしたら、いま Google スプレッドシート上で翻訳するつもりになっているファイルを手放しても大丈夫ですよー？😄
> 
> 一旦、次の週末まで待ってから、10/29（月）くらいから巻き取って行こうと考えています〜

 @inouetakuya  すみません! 大変遅くなりました。
自分、今夜やりまーす!

**Comment by inouetakuya** [comment]
@resessh 

@resessh さんは既に翻訳していただいていますし、私、今日ちょうど手があいているので、

* api/nuxt-render-route.md 

の翻訳もらっちゃいますねー 😄

**Comment by inouetakuya** [comment]
ふおおおお！！ついに対象としていたファイルがすべて翻訳されました！！！:tada::tada::tada:

* https://docs.google.com/spreadsheets/d/1fj41JP8nhRknwvaUuBDDXiRjxACRfHBxY63v--tcNMI/edit?usp=sharing

![tumblr_mregdf7bc01r1mywzo1_400](https://user-images.githubusercontent.com/634357/47700629-8cab3d00-dc5a-11e8-9aad-47372cde4672.gif)

クローズしまっす！！！
