### ISSUE TITLE
en/guide/vuex-store.md の翻訳

### ISSUE THREAD

**Issue by aytdm** [vuejs-jp/ja.docs.nuxtjs#52]
### 翻訳対象

/guide/vuex-store.md
b000302..e53272a 間の差分の翻訳をお願いします。
詳細な差分は `git diff` コマンドで見るか、いのうえさんが用意してくださった[こちらの gist](https://gist.github.com/inouetakuya/4b231c5e634e5e7d0f80856d3eb3691d) を参照してください。

### 翻訳の流れ

まずはこの issue にコメントで翻訳する意思表示をお願いします🙋
それ以降の流れは [#37ドキュメント翻訳 2019 春の陣](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/37#issue-415991098) を参照してください。

### 翻訳スタイル

Vue.js に合わせています。
スタイルについては[こちら](https://github.com/vuejs-jp/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md#%E7%BF%BB%E8%A8%B3%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB)を参照してください。

**Comment by aytdm** [comment]
https://github.com/nuxt/docs/pull/1174 でファイルを更新しているので、merge され次第 翻訳をお願いします:pray:

**Comment by resessh** [comment]
これやりたいです！

**Comment by resessh** [comment]
こちら差分すでにjaにも入っており、変更ありませんでした… 🙏

**Comment by aytdm** [comment]
ご確認ありがとうございます！おっしゃる通り b000302..e53272a 間の差分は反映されていますね。
ただ、e53272a 時点の en と ja 間で差分があるようので対応していただけないでしょうか？:bow:

+ [e53272a/en/guide/vuex-store.md](https://github.com/vuejs-jp/ja.docs.nuxtjs/blob/e53272a68e3a4ac45373ec333b14009f45dbf29b/en/guide/vuex-store.md)
+ [e53272a/ja/guide/vuex-store.md](https://github.com/vuejs-jp/ja.docs.nuxtjs/blob/e53272a68e3a4ac45373ec333b14009f45dbf29b/ja/guide/vuex-store.md)

**Comment by resessh** [comment]
@aytdm 見落としてました！やります！
