### ISSUE TITLE
en/faq/menu.json の翻訳

### ISSUE THREAD

**Issue by aytdm** [vuejs-jp/ja.docs.nuxtjs#55]
### 翻訳対象

/faq/menu.json 
b000302..e53272a 間の差分の翻訳をお願いします。
詳細な差分は `git diff` コマンドで見るか、いのうえさんが用意してくださった[こちらの gist](https://gist.github.com/inouetakuya/4b231c5e634e5e7d0f80856d3eb3691d) を参照してください。

**Comment by aytdm** [comment]
FYI：https://github.com/nuxt/docs/pull/1174 でファイル更新の PR を出しています。

**Comment by serima** [comment]
こちら対応します！
