### ISSUE TITLE
デイリーで nuxt/docs の master と同期するためのバッチを書く

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.docs.nuxtjs#7]
最新の情報を取り入れた上で翻訳すべきものがわかるように。

**Comment by potato4d** [comment]
@inouetakuya 
本家に PR を出すことに今はなっているので、こちらは更新がわかりやすいような作りにすることを目的にすると良いのではないかと考えています。
そのために、一旦 lang-ja ではなく master をデフォルトブランチとしてしまって、常に同期をするような体制を整えたいのですが、デフォルトブランチを変えてしまってもよろしいでしょうか？

**Comment by inouetakuya** [comment]
> そのために、一旦 lang-ja ではなく master をデフォルトブランチとしてしまって、常に同期をするような体制を整えたいのですが、デフォルトブランチを変えてしまってもよろしいでしょうか？

ああ、これ、わたしもそうしたいと思っていました。デフォルトブランチ変えちゃいますねー

**Comment by potato4d** [comment]
変わったのでクローズ。
