### ISSUE TITLE
asyncData メソッドの注意書きについて

### ISSUE THREAD

**Issue by fumuumuf** [vuejs-jp/ja.docs.nuxtjs#8]
翻訳ありがとうございます.
以下のページについてご確認させてください.

https://github.com/vuejs-jp/ja.docs.nuxtjs/blob/master/ja/api/index.md

> `data` メソッド内で、コンポーネントのインスタンスに `this` を経由してアクセスしては**いけません**。なぜなら `data` メソッドはコンポーネントが **インスタンス化される前に** 呼び出されるためです。

とありますが, `data` ではなく `asyncData` ではないでしょうか？

**Comment by aytdm** [comment]
こんばんは。issueありがとうございます！
確かにご指摘の通りですね。

現在、未翻訳のページを一斉翻訳しているので、そちらで対応します。
暫しお待ちください〜

**Comment by aytdm** [comment]
@fumuumuf 
本件、shika358 さんが対応してくださいました！
ご確認よろしくおねがいします

**Comment by fumuumuf** [comment]
確認しました. ご対応ありがとうございました！
