### ISSUE TITLE
Nuxt 2.0 ドキュメント翻訳

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.docs.nuxtjs#9]
とりあえず 2018 秋の陣のメンバーにメンション。

@potato4d @aytdm @hisako135 @resessh @tell-k @shika358 @ryamakuchi @ryota-yamamoto @53able @rascate

2.0 ブランチが master にマージされましたので（ニッコリ）、差分を翻訳していきましょうー！:muscle:

## 一緒にやっていきたい人！

この Issue にその旨をコメントしてください！🙏

（コメントをすると、自動的にこの Issue を subscribe するようになります）

今後の案内等はこの Issue にコメントするかたちで行います。

## スケジュール

* [x] GitHub プロジェクトを作成する（10/26 金） @inouetakuya
* [x] 翻訳対象ファイルについて、1ファイル 1Issue 立てて、GitHub プロジェクトに結び付ける（10/28 日） @inouetakuya
* [x] 一緒にやっていく人を募る
* [x] 翻訳する（10/28 日 〜 11/30 金）

## 翻訳の流れ

よく分からない点がありましたら、この Issue でカジュアルに質問してください〜 :smile:

### 翻訳する人

(1) GitHub プロジェクト（ https://github.com/vuejs-jp/ja.docs.nuxtjs/projects/1 ）を開いて **「未アサイン」となっている Issue** を選んで、**自分が翻訳を担当する旨を当該未アサイン Issue 内にコメント**する
(2) `nuxt/docs` リポジトリと各自 Fork してください
(3) 翻訳して `nuxt/docs:master` ブランチに対してプルリクを出す

* プルリクタイトルに `ja: ` というプレフィックスを付けてください
* まだ翻訳作業途中のときは `[WIP] ja: ` を付けてください
* プルリク冒頭で @inouetakuya @potato4d @aytdm に対してメンションを飛ばしてください
* コメント等は、英語で表現するのが難しいケースもあると思うので、必ずしも無理して英語でする必要はありません

(4) https://github.com/vuejs-jp/ja.docs.nuxtjs/projects/1 内の Issue を「Needs review」に移動させる

### レビューする人（@inouetakuya @potato4d @aytdm 以外もお願いします）

(5) `nuxt/docs` 内の日本語翻訳プルリクをレビューする。マージして問題なさそうだと思ったらその旨をコメントする

### マージする人（@inouetakuya @potato4d @aytdm）

(6) マージしてよい状態になったプルリクをマージする
(7) https://github.com/vuejs-jp/ja.docs.nuxtjs/projects/1 内の Issue をクローズする（= 自動的に「Done」に移動される）

## 翻訳対象ファイル一覧

Merge branch '2.0' · nuxt/docs@b000302
https://github.com/nuxt/docs/commit/b000302bd83a2bef8c00979c98ab1c2d62f2dcb0

diff | ファイル名
----: | ----
+3 −1 | en/api/components-nuxt-child.md
+230 −141 | en/api/configuration-build.md
+4 −0 | en/api/configuration-env.md
+1 −1 | en/api/configuration-generate.md
+38 −0 | en/api/configuration-hooks.md
+10 −3 | en/api/configuration-modulesdir.md
+16 −4 | en/api/configuration-render.md
+49 −0 | en/api/configuration-server.md
+3 −3 | en/api/internals-renderer.md
+6 −8 | en/api/internals.md
+2 −0 | en/api/menu.json
+28 −1 | en/api/pages-validate.md
+1 −2 | en/examples/seo-html-head.md
+308 −0 | en/faq/deployment-aws-s3-cloudfront.md
+43 −22 | en/faq/host-port.md
+7 −6 | en/faq/menu.json
+2 −0 | en/guide/commands.md
+13 −0 | en/guide/configuration.md
+5 −3 | en/guide/contribution-guide.md
+11 −14 | en/guide/index.md
+29 −10 | en/guide/installation.md
+114 −13 | en/guide/plugins.md
+1 −1 | en/guide/routing.md
+1 −1 | en/lang.json

**Comment by resessh** [comment]
💪

**Comment by ryota-yamamoto** [comment]
💪

**Comment by MozyOk** [comment]
💪

**Comment by tell-k** [comment]
💪

**Comment by aytdm** [comment]
@inouetakuya 
> 翻訳対象ファイルについて、1ファイル 1Issue 立てて、GitHub プロジェクトに結び付ける（10/28 日）

量があるので、よければ私も分担します

**Comment by inouetakuya** [comment]
@aytdm 

> 量があるので、よければ私も分担します

ありがとうございます！（めちゃくちゃ嬉しかったです！）

勢いに乗っていたので全部できました！:muscle:

**Comment by rascate** [comment]
💪

**Comment by shika358** [comment]
🙋‍♂️

**Comment by watkazuki** [comment]
🙋‍♂️

**Comment by teinen** [comment]
🙋

**Comment by hivesbee** [comment]
私もやってみたいですー 🙋

**Comment by aytdm** [comment]
今回翻訳対象のファイル、担当者が全て決まりました～！！
ありがとうございます:satisfied:

**Comment by 53able** [comment]
@inouetakuya すみません。体調をめちゃくちゃ崩しておりまして、誰かにフォローしていただくか、来週まで猶予いただきたいですー。

**Comment by potato4d** [comment]
@53able 
こちらで引き継ぎましょうか？土日でやりますよ〜

**Comment by 53able** [comment]
@potato4d お願いしまーす！

**Comment by tell-k** [comment]
@potato4d  もしかしたら気づいてないかもしれないので、一応確認ですが、@53able さんがやる予定だった https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/11 を @potato4d さんが対応をしていただけるっていう認識であってますかね？

もし忙しそうで対応が難しいとかであれば、私も今週末とか対応可能ですので、遠慮なく言ってくださいー。

**Comment by potato4d** [comment]
@tell-k 
申し訳ないです、ちょっとまだ未完でした 🙇 
Ad-Cal が明日なので作業しつつになるのでもしかしたら水曜夜とかになるかもしれませんが、終わらせますー。

**Comment by tell-k** [comment]
@potato4d  こちらこそ急かすようなまねしてすいません 🙇 
既にお気づきであれば何も問題ありませんので、ゆっくり対応していただいて大丈夫かと思いますー。
対応ありがとうございますー！

**Comment by aytdm** [comment]
@potato4d こちら進捗いかがでしょうか。お忙しいようでしたら私のほうでも対応できます～

**Comment by potato4d** [comment]
@aytdm 

すみません、火曜日までにできそうになかったら駄目な気がするのでお願いします！それまでに完了できるよう、つとめます。

**Comment by potato4d** [comment]
@inouetakuya @aytdm 
他なければ一旦これクローズしちゃいましょう！

**Comment by inouetakuya** [comment]
この Issue で予定していた範囲は完了です！（en/ との差分はまだありますが、それは別途やりましょう）

みなさん、おつかれさまでした！:tada:
